/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ErrorType = IDL.Variant({
  'toolFailure' : IDL.Null,
  'logic' : IDL.Null,
  'timeout' : IDL.Null,
  'parsing' : IDL.Null,
});
export const ErrorLogDTO = IDL.Record({
  'resolved' : IDL.Bool,
  'errorType' : ErrorType,
  'message' : IDL.Text,
});
export const LogStatus = IDL.Variant({
  'completed' : IDL.Null,
  'error' : IDL.Null,
  'running' : IDL.Null,
});
export const LogEntryInput = IDL.Record({
  'status' : LogStatus,
  'message' : IDL.Text,
});
export const MemoryType = IDL.Variant({
  'action' : IDL.Null,
  'preference' : IDL.Null,
  'session' : IDL.Null,
});
export const MemoryEntryDTO = IDL.Record({
  'content' : IDL.Text,
  'memoryType' : MemoryType,
});
export const Role = IDL.Variant({ 'agent' : IDL.Null, 'user' : IDL.Null });
export const TaskType = IDL.Variant({
  'deployment' : IDL.Null,
  'search' : IDL.Null,
  'coding' : IDL.Null,
  'analysis' : IDL.Null,
});
export const MessageInput = IDL.Record({
  'content' : IDL.Text,
  'role' : Role,
  'taskType' : TaskType,
});
export const PlanStepStatus = IDL.Variant({
  'pending' : IDL.Null,
  'done' : IDL.Null,
  'error' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const PlanStepDTO = IDL.Record({
  'status' : PlanStepStatus,
  'description' : IDL.Text,
  'stepNumber' : IDL.Nat,
});
export const StrategyImprovementDTO = IDL.Record({
  'beforeStrategy' : IDL.Text,
  'changeDescription' : IDL.Text,
  'afterStrategy' : IDL.Text,
});
export const Tool = IDL.Variant({
  'deployment' : IDL.Null,
  'fileSystem' : IDL.Null,
  'gitHub' : IDL.Null,
});
export const ToolConnectionDTO = IDL.Record({
  'tool' : Tool,
  'connected' : IDL.Bool,
});
export const RunMode = IDL.Variant({
  'normal' : IDL.Null,
  'deep' : IDL.Null,
  'caffeine' : IDL.Null,
});
export const AgentConfig = IDL.Record({
  'learningScore' : IDL.Nat,
  'mode' : RunMode,
});
export const Time = IDL.Int;
export const ErrorLog = IDL.Record({
  'resolved' : IDL.Bool,
  'errorType' : ErrorType,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const LogEntry = IDL.Record({
  'status' : LogStatus,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const MemoryEntry = IDL.Record({
  'content' : IDL.Text,
  'timestamp' : Time,
  'memoryType' : MemoryType,
});
export const Message = IDL.Record({
  'content' : IDL.Text,
  'role' : Role,
  'taskType' : TaskType,
  'timestamp' : Time,
});
export const PlanStep = IDL.Record({
  'status' : PlanStepStatus,
  'description' : IDL.Text,
  'stepNumber' : IDL.Nat,
});
export const StrategyImprovement = IDL.Record({
  'beforeStrategy' : IDL.Text,
  'timestamp' : Time,
  'changeDescription' : IDL.Text,
  'afterStrategy' : IDL.Text,
});
export const ToolConnection = IDL.Record({
  'tool' : Tool,
  'connected' : IDL.Bool,
});
export const AgentConfigDTO = IDL.Record({
  'learningScore' : IDL.Nat,
  'mode' : RunMode,
});

export const idlService = IDL.Service({
  'addErrorLog' : IDL.Func([ErrorLogDTO], [], []),
  'addLogEntry' : IDL.Func([LogEntryInput], [], []),
  'addMemoryEntry' : IDL.Func([MemoryEntryDTO], [], []),
  'addMessage' : IDL.Func([MessageInput], [], []),
  'addPlanStep' : IDL.Func([PlanStepDTO], [], []),
  'addStrategyImprovement' : IDL.Func([StrategyImprovementDTO], [], []),
  'addTaskAgent' : IDL.Func([TaskType, IDL.Principal], [], []),
  'addToolConnection' : IDL.Func([ToolConnectionDTO], [], []),
  'clearAllData' : IDL.Func([], [], []),
  'clearLogEntries' : IDL.Func([], [], []),
  'clearMessages' : IDL.Func([], [], []),
  'getAgentConfig' : IDL.Func([], [AgentConfig], ['query']),
  'getAllErrorLogs' : IDL.Func([], [IDL.Vec(ErrorLog)], ['query']),
  'getAllLogEntries' : IDL.Func([], [IDL.Vec(LogEntry)], ['query']),
  'getAllMemoryEntries' : IDL.Func([], [IDL.Vec(MemoryEntry)], ['query']),
  'getAllMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getAllPlanSteps' : IDL.Func([], [IDL.Vec(PlanStep)], ['query']),
  'getAllStrategyImprovements' : IDL.Func(
      [],
      [IDL.Vec(StrategyImprovement)],
      ['query'],
    ),
  'getAllToolConnections' : IDL.Func([], [IDL.Vec(ToolConnection)], ['query']),
  'getTaskAgent' : IDL.Func([TaskType], [IDL.Principal], ['query']),
  'incrementLearningScore' : IDL.Func([], [IDL.Nat], []),
  'updateAgentConfig' : IDL.Func([AgentConfigDTO], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ErrorType = IDL.Variant({
    'toolFailure' : IDL.Null,
    'logic' : IDL.Null,
    'timeout' : IDL.Null,
    'parsing' : IDL.Null,
  });
  const ErrorLogDTO = IDL.Record({
    'resolved' : IDL.Bool,
    'errorType' : ErrorType,
    'message' : IDL.Text,
  });
  const LogStatus = IDL.Variant({
    'completed' : IDL.Null,
    'error' : IDL.Null,
    'running' : IDL.Null,
  });
  const LogEntryInput = IDL.Record({
    'status' : LogStatus,
    'message' : IDL.Text,
  });
  const MemoryType = IDL.Variant({
    'action' : IDL.Null,
    'preference' : IDL.Null,
    'session' : IDL.Null,
  });
  const MemoryEntryDTO = IDL.Record({
    'content' : IDL.Text,
    'memoryType' : MemoryType,
  });
  const Role = IDL.Variant({ 'agent' : IDL.Null, 'user' : IDL.Null });
  const TaskType = IDL.Variant({
    'deployment' : IDL.Null,
    'search' : IDL.Null,
    'coding' : IDL.Null,
    'analysis' : IDL.Null,
  });
  const MessageInput = IDL.Record({
    'content' : IDL.Text,
    'role' : Role,
    'taskType' : TaskType,
  });
  const PlanStepStatus = IDL.Variant({
    'pending' : IDL.Null,
    'done' : IDL.Null,
    'error' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const PlanStepDTO = IDL.Record({
    'status' : PlanStepStatus,
    'description' : IDL.Text,
    'stepNumber' : IDL.Nat,
  });
  const StrategyImprovementDTO = IDL.Record({
    'beforeStrategy' : IDL.Text,
    'changeDescription' : IDL.Text,
    'afterStrategy' : IDL.Text,
  });
  const Tool = IDL.Variant({
    'deployment' : IDL.Null,
    'fileSystem' : IDL.Null,
    'gitHub' : IDL.Null,
  });
  const ToolConnectionDTO = IDL.Record({
    'tool' : Tool,
    'connected' : IDL.Bool,
  });
  const RunMode = IDL.Variant({
    'normal' : IDL.Null,
    'deep' : IDL.Null,
    'caffeine' : IDL.Null,
  });
  const AgentConfig = IDL.Record({
    'learningScore' : IDL.Nat,
    'mode' : RunMode,
  });
  const Time = IDL.Int;
  const ErrorLog = IDL.Record({
    'resolved' : IDL.Bool,
    'errorType' : ErrorType,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const LogEntry = IDL.Record({
    'status' : LogStatus,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const MemoryEntry = IDL.Record({
    'content' : IDL.Text,
    'timestamp' : Time,
    'memoryType' : MemoryType,
  });
  const Message = IDL.Record({
    'content' : IDL.Text,
    'role' : Role,
    'taskType' : TaskType,
    'timestamp' : Time,
  });
  const PlanStep = IDL.Record({
    'status' : PlanStepStatus,
    'description' : IDL.Text,
    'stepNumber' : IDL.Nat,
  });
  const StrategyImprovement = IDL.Record({
    'beforeStrategy' : IDL.Text,
    'timestamp' : Time,
    'changeDescription' : IDL.Text,
    'afterStrategy' : IDL.Text,
  });
  const ToolConnection = IDL.Record({ 'tool' : Tool, 'connected' : IDL.Bool });
  const AgentConfigDTO = IDL.Record({
    'learningScore' : IDL.Nat,
    'mode' : RunMode,
  });
  
  return IDL.Service({
    'addErrorLog' : IDL.Func([ErrorLogDTO], [], []),
    'addLogEntry' : IDL.Func([LogEntryInput], [], []),
    'addMemoryEntry' : IDL.Func([MemoryEntryDTO], [], []),
    'addMessage' : IDL.Func([MessageInput], [], []),
    'addPlanStep' : IDL.Func([PlanStepDTO], [], []),
    'addStrategyImprovement' : IDL.Func([StrategyImprovementDTO], [], []),
    'addTaskAgent' : IDL.Func([TaskType, IDL.Principal], [], []),
    'addToolConnection' : IDL.Func([ToolConnectionDTO], [], []),
    'clearAllData' : IDL.Func([], [], []),
    'clearLogEntries' : IDL.Func([], [], []),
    'clearMessages' : IDL.Func([], [], []),
    'getAgentConfig' : IDL.Func([], [AgentConfig], ['query']),
    'getAllErrorLogs' : IDL.Func([], [IDL.Vec(ErrorLog)], ['query']),
    'getAllLogEntries' : IDL.Func([], [IDL.Vec(LogEntry)], ['query']),
    'getAllMemoryEntries' : IDL.Func([], [IDL.Vec(MemoryEntry)], ['query']),
    'getAllMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getAllPlanSteps' : IDL.Func([], [IDL.Vec(PlanStep)], ['query']),
    'getAllStrategyImprovements' : IDL.Func(
        [],
        [IDL.Vec(StrategyImprovement)],
        ['query'],
      ),
    'getAllToolConnections' : IDL.Func(
        [],
        [IDL.Vec(ToolConnection)],
        ['query'],
      ),
    'getTaskAgent' : IDL.Func([TaskType], [IDL.Principal], ['query']),
    'incrementLearningScore' : IDL.Func([], [IDL.Nat], []),
    'updateAgentConfig' : IDL.Func([AgentConfigDTO], [], []),
  });
};

export const init = ({ IDL }) => { return []; };