/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AgentConfig { 'learningScore' : bigint, 'mode' : RunMode }
export interface AgentConfigDTO { 'learningScore' : bigint, 'mode' : RunMode }
export interface ErrorLog {
  'resolved' : boolean,
  'errorType' : ErrorType,
  'message' : string,
  'timestamp' : Time,
}
export interface ErrorLogDTO {
  'resolved' : boolean,
  'errorType' : ErrorType,
  'message' : string,
}
export type ErrorType = { 'toolFailure' : null } |
  { 'logic' : null } |
  { 'timeout' : null } |
  { 'parsing' : null };
export interface LogEntry {
  'status' : LogStatus,
  'message' : string,
  'timestamp' : Time,
}
export interface LogEntryInput { 'status' : LogStatus, 'message' : string }
export type LogStatus = { 'completed' : null } |
  { 'error' : null } |
  { 'running' : null };
export interface MemoryEntry {
  'content' : string,
  'timestamp' : Time,
  'memoryType' : MemoryType,
}
export interface MemoryEntryDTO {
  'content' : string,
  'memoryType' : MemoryType,
}
export type MemoryType = { 'action' : null } |
  { 'preference' : null } |
  { 'session' : null };
export interface Message {
  'content' : string,
  'role' : Role,
  'taskType' : TaskType,
  'timestamp' : Time,
}
export interface MessageInput {
  'content' : string,
  'role' : Role,
  'taskType' : TaskType,
}
export interface PlanStep {
  'status' : PlanStepStatus,
  'description' : string,
  'stepNumber' : bigint,
}
export interface PlanStepDTO {
  'status' : PlanStepStatus,
  'description' : string,
  'stepNumber' : bigint,
}
export type PlanStepStatus = { 'pending' : null } |
  { 'done' : null } |
  { 'error' : null } |
  { 'inProgress' : null };
export type Role = { 'agent' : null } |
  { 'user' : null };
export type RunMode = { 'normal' : null } |
  { 'deep' : null } |
  { 'caffeine' : null };
export interface StrategyImprovement {
  'beforeStrategy' : string,
  'timestamp' : Time,
  'changeDescription' : string,
  'afterStrategy' : string,
}
export interface StrategyImprovementDTO {
  'beforeStrategy' : string,
  'changeDescription' : string,
  'afterStrategy' : string,
}
export type TaskType = { 'deployment' : null } |
  { 'search' : null } |
  { 'coding' : null } |
  { 'analysis' : null };
export type Time = bigint;
export type Tool = { 'deployment' : null } |
  { 'fileSystem' : null } |
  { 'gitHub' : null };
export interface ToolConnection { 'tool' : Tool, 'connected' : boolean }
export interface ToolConnectionDTO { 'tool' : Tool, 'connected' : boolean }
export interface _SERVICE {
  'addErrorLog' : ActorMethod<[ErrorLogDTO], undefined>,
  'addLogEntry' : ActorMethod<[LogEntryInput], undefined>,
  'addMemoryEntry' : ActorMethod<[MemoryEntryDTO], undefined>,
  'addMessage' : ActorMethod<[MessageInput], undefined>,
  'addPlanStep' : ActorMethod<[PlanStepDTO], undefined>,
  'addStrategyImprovement' : ActorMethod<[StrategyImprovementDTO], undefined>,
  'addTaskAgent' : ActorMethod<[TaskType, Principal], undefined>,
  'addToolConnection' : ActorMethod<[ToolConnectionDTO], undefined>,
  'clearAllData' : ActorMethod<[], undefined>,
  'clearLogEntries' : ActorMethod<[], undefined>,
  'clearMessages' : ActorMethod<[], undefined>,
  'getAgentConfig' : ActorMethod<[], AgentConfig>,
  'getAllErrorLogs' : ActorMethod<[], Array<ErrorLog>>,
  'getAllLogEntries' : ActorMethod<[], Array<LogEntry>>,
  'getAllMemoryEntries' : ActorMethod<[], Array<MemoryEntry>>,
  'getAllMessages' : ActorMethod<[], Array<Message>>,
  'getAllPlanSteps' : ActorMethod<[], Array<PlanStep>>,
  'getAllStrategyImprovements' : ActorMethod<[], Array<StrategyImprovement>>,
  'getAllToolConnections' : ActorMethod<[], Array<ToolConnection>>,
  'getTaskAgent' : ActorMethod<[TaskType], Principal>,
  'incrementLearningScore' : ActorMethod<[], bigint>,
  'updateAgentConfig' : ActorMethod<[AgentConfigDTO], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];