/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AgentConfig {
    learningScore: bigint;
    mode: RunMode;
}
export interface AgentConfigDTO {
    learningScore: bigint;
    mode: RunMode;
}
export type Time = bigint;
export interface MemoryEntryDTO {
    content: string;
    memoryType: MemoryType;
}
export interface MemoryEntry {
    content: string;
    timestamp: Time;
    memoryType: MemoryType;
}
export interface StrategyImprovementDTO {
    beforeStrategy: string;
    changeDescription: string;
    afterStrategy: string;
}
export interface StrategyImprovement {
    beforeStrategy: string;
    timestamp: Time;
    changeDescription: string;
    afterStrategy: string;
}
export interface LogEntryInput {
    status: LogStatus;
    message: string;
}
export interface LogEntry {
    status: LogStatus;
    message: string;
    timestamp: Time;
}
export interface ErrorLog {
    resolved: boolean;
    errorType: ErrorType;
    message: string;
    timestamp: Time;
}
export interface ErrorLogDTO {
    resolved: boolean;
    errorType: ErrorType;
    message: string;
}
export interface Message {
    content: string;
    role: Role;
    taskType: TaskType;
    timestamp: Time;
}
export interface ToolConnectionDTO {
    tool: Tool;
    connected: boolean;
}
export interface PlanStep {
    status: PlanStepStatus;
    description: string;
    stepNumber: bigint;
}
export interface ToolConnection {
    tool: Tool;
    connected: boolean;
}
export interface MessageInput {
    content: string;
    role: Role;
    taskType: TaskType;
}
export interface PlanStepDTO {
    status: PlanStepStatus;
    description: string;
    stepNumber: bigint;
}
export enum ErrorType {
    toolFailure = "toolFailure",
    logic = "logic",
    timeout = "timeout",
    parsing = "parsing"
}
export enum LogStatus {
    completed = "completed",
    error = "error",
    running = "running"
}
export enum MemoryType {
    action = "action",
    preference = "preference",
    session = "session"
}
export enum PlanStepStatus {
    pending = "pending",
    done = "done",
    error = "error",
    inProgress = "inProgress"
}
export enum Role {
    agent = "agent",
    user = "user"
}
export enum RunMode {
    normal = "normal",
    deep = "deep",
    caffeine = "caffeine"
}
export enum TaskType {
    deployment = "deployment",
    search = "search",
    coding = "coding",
    analysis = "analysis"
}
export enum Tool {
    deployment = "deployment",
    fileSystem = "fileSystem",
    gitHub = "gitHub"
}
export interface backendInterface {
    addErrorLog(input: ErrorLogDTO): Promise<void>;
    addLogEntry(input: LogEntryInput): Promise<void>;
    addMemoryEntry(input: MemoryEntryDTO): Promise<void>;
    addMessage(input: MessageInput): Promise<void>;
    addPlanStep(stepInput: PlanStepDTO): Promise<void>;
    addStrategyImprovement(input: StrategyImprovementDTO): Promise<void>;
    addTaskAgent(taskType: TaskType, agent: Principal): Promise<void>;
    addToolConnection(input: ToolConnectionDTO): Promise<void>;
    clearAllData(): Promise<void>;
    clearLogEntries(): Promise<void>;
    clearMessages(): Promise<void>;
    getAgentConfig(): Promise<AgentConfig>;
    getAllErrorLogs(): Promise<Array<ErrorLog>>;
    getAllLogEntries(): Promise<Array<LogEntry>>;
    getAllMemoryEntries(): Promise<Array<MemoryEntry>>;
    getAllMessages(): Promise<Array<Message>>;
    getAllPlanSteps(): Promise<Array<PlanStep>>;
    getAllStrategyImprovements(): Promise<Array<StrategyImprovement>>;
    getAllToolConnections(): Promise<Array<ToolConnection>>;
    getTaskAgent(taskType: TaskType): Promise<Principal>;
    incrementLearningScore(): Promise<bigint>;
    updateAgentConfig(newConfig: AgentConfigDTO): Promise<void>;
}
import type { AgentConfig as _AgentConfig, AgentConfigDTO as _AgentConfigDTO, ErrorLog as _ErrorLog, ErrorLogDTO as _ErrorLogDTO, ErrorType as _ErrorType, LogEntry as _LogEntry, LogEntryInput as _LogEntryInput, LogStatus as _LogStatus, MemoryEntry as _MemoryEntry, MemoryEntryDTO as _MemoryEntryDTO, MemoryType as _MemoryType, Message as _Message, MessageInput as _MessageInput, PlanStep as _PlanStep, PlanStepDTO as _PlanStepDTO, PlanStepStatus as _PlanStepStatus, Role as _Role, RunMode as _RunMode, TaskType as _TaskType, Time as _Time, Tool as _Tool, ToolConnection as _ToolConnection, ToolConnectionDTO as _ToolConnectionDTO } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addErrorLog(arg0: ErrorLogDTO): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addErrorLog(to_candid_ErrorLogDTO_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addErrorLog(to_candid_ErrorLogDTO_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addLogEntry(arg0: LogEntryInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addLogEntry(to_candid_LogEntryInput_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLogEntry(to_candid_LogEntryInput_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addMemoryEntry(arg0: MemoryEntryDTO): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMemoryEntry(to_candid_MemoryEntryDTO_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMemoryEntry(to_candid_MemoryEntryDTO_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addMessage(arg0: MessageInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMessage(to_candid_MessageInput_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMessage(to_candid_MessageInput_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addPlanStep(arg0: PlanStepDTO): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPlanStep(to_candid_PlanStepDTO_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPlanStep(to_candid_PlanStepDTO_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addStrategyImprovement(arg0: StrategyImprovementDTO): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addStrategyImprovement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStrategyImprovement(arg0);
            return result;
        }
    }
    async addTaskAgent(arg0: TaskType, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTaskAgent(to_candid_TaskType_n17(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTaskAgent(to_candid_TaskType_n17(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async addToolConnection(arg0: ToolConnectionDTO): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToolConnection(to_candid_ToolConnectionDTO_n23(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToolConnection(to_candid_ToolConnectionDTO_n23(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async clearAllData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAllData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAllData();
            return result;
        }
    }
    async clearLogEntries(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearLogEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearLogEntries();
            return result;
        }
    }
    async clearMessages(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearMessages();
            return result;
        }
    }
    async getAgentConfig(): Promise<AgentConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getAgentConfig();
                return from_candid_AgentConfig_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAgentConfig();
            return from_candid_AgentConfig_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllErrorLogs(): Promise<Array<ErrorLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllErrorLogs();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllErrorLogs();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllLogEntries(): Promise<Array<LogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLogEntries();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLogEntries();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMemoryEntries(): Promise<Array<MemoryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMemoryEntries();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMemoryEntries();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMessages(): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMessages();
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMessages();
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPlanSteps(): Promise<Array<PlanStep>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPlanSteps();
                return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPlanSteps();
            return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllStrategyImprovements(): Promise<Array<StrategyImprovement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStrategyImprovements();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStrategyImprovements();
            return result;
        }
    }
    async getAllToolConnections(): Promise<Array<ToolConnection>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllToolConnections();
                return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllToolConnections();
            return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTaskAgent(arg0: TaskType): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.getTaskAgent(to_candid_TaskType_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTaskAgent(to_candid_TaskType_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async incrementLearningScore(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementLearningScore();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementLearningScore();
            return result;
        }
    }
    async updateAgentConfig(arg0: AgentConfigDTO): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAgentConfig(to_candid_AgentConfigDTO_n63(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAgentConfig(to_candid_AgentConfigDTO_n63(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_AgentConfig_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AgentConfig): AgentConfig {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_ErrorLog_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ErrorLog): ErrorLog {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_ErrorType_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ErrorType): ErrorType {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_LogEntry_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LogEntry): LogEntry {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_LogStatus_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LogStatus): LogStatus {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_MemoryEntry_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MemoryEntry): MemoryEntry {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_MemoryType_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MemoryType): MemoryType {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function from_candid_Message_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Message): Message {
    return from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid_PlanStepStatus_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlanStepStatus): PlanStepStatus {
    return from_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function from_candid_PlanStep_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlanStep): PlanStep {
    return from_candid_record_n55(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function from_candid_RunMode_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RunMode): RunMode {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_TaskType_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskType): TaskType {
    return from_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function from_candid_ToolConnection_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ToolConnection): ToolConnection {
    return from_candid_record_n60(_uploadFile, _downloadFile, value);
}
function from_candid_Tool_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Tool): Tool {
    return from_candid_variant_n62(_uploadFile, _downloadFile, value);
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    learningScore: bigint;
    mode: _RunMode;
}): {
    learningScore: bigint;
    mode: RunMode;
} {
    return {
        learningScore: value.learningScore,
        mode: from_candid_RunMode_n29(_uploadFile, _downloadFile, value.mode)
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resolved: boolean;
    errorType: _ErrorType;
    message: string;
    timestamp: _Time;
}): {
    resolved: boolean;
    errorType: ErrorType;
    message: string;
    timestamp: Time;
} {
    return {
        resolved: value.resolved,
        errorType: from_candid_ErrorType_n34(_uploadFile, _downloadFile, value.errorType),
        message: value.message,
        timestamp: value.timestamp
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _LogStatus;
    message: string;
    timestamp: _Time;
}): {
    status: LogStatus;
    message: string;
    timestamp: Time;
} {
    return {
        status: from_candid_LogStatus_n39(_uploadFile, _downloadFile, value.status),
        message: value.message,
        timestamp: value.timestamp
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    content: string;
    timestamp: _Time;
    memoryType: _MemoryType;
}): {
    content: string;
    timestamp: Time;
    memoryType: MemoryType;
} {
    return {
        content: value.content,
        timestamp: value.timestamp,
        memoryType: from_candid_MemoryType_n44(_uploadFile, _downloadFile, value.memoryType)
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    content: string;
    role: _Role;
    taskType: _TaskType;
    timestamp: _Time;
}): {
    content: string;
    role: Role;
    taskType: TaskType;
    timestamp: Time;
} {
    return {
        content: value.content,
        role: from_candid_Role_n49(_uploadFile, _downloadFile, value.role),
        taskType: from_candid_TaskType_n51(_uploadFile, _downloadFile, value.taskType),
        timestamp: value.timestamp
    };
}
function from_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _PlanStepStatus;
    description: string;
    stepNumber: bigint;
}): {
    status: PlanStepStatus;
    description: string;
    stepNumber: bigint;
} {
    return {
        status: from_candid_PlanStepStatus_n56(_uploadFile, _downloadFile, value.status),
        description: value.description,
        stepNumber: value.stepNumber
    };
}
function from_candid_record_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tool: _Tool;
    connected: boolean;
}): {
    tool: Tool;
    connected: boolean;
} {
    return {
        tool: from_candid_Tool_n61(_uploadFile, _downloadFile, value.tool),
        connected: value.connected
    };
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    normal: null;
} | {
    deep: null;
} | {
    caffeine: null;
}): RunMode {
    return "normal" in value ? RunMode.normal : "deep" in value ? RunMode.deep : "caffeine" in value ? RunMode.caffeine : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    toolFailure: null;
} | {
    logic: null;
} | {
    timeout: null;
} | {
    parsing: null;
}): ErrorType {
    return "toolFailure" in value ? ErrorType.toolFailure : "logic" in value ? ErrorType.logic : "timeout" in value ? ErrorType.timeout : "parsing" in value ? ErrorType.parsing : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: null;
} | {
    error: null;
} | {
    running: null;
}): LogStatus {
    return "completed" in value ? LogStatus.completed : "error" in value ? LogStatus.error : "running" in value ? LogStatus.running : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    action: null;
} | {
    preference: null;
} | {
    session: null;
}): MemoryType {
    return "action" in value ? MemoryType.action : "preference" in value ? MemoryType.preference : "session" in value ? MemoryType.session : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    agent: null;
} | {
    user: null;
}): Role {
    return "agent" in value ? Role.agent : "user" in value ? Role.user : value;
}
function from_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    deployment: null;
} | {
    search: null;
} | {
    coding: null;
} | {
    analysis: null;
}): TaskType {
    return "deployment" in value ? TaskType.deployment : "search" in value ? TaskType.search : "coding" in value ? TaskType.coding : "analysis" in value ? TaskType.analysis : value;
}
function from_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    done: null;
} | {
    error: null;
} | {
    inProgress: null;
}): PlanStepStatus {
    return "pending" in value ? PlanStepStatus.pending : "done" in value ? PlanStepStatus.done : "error" in value ? PlanStepStatus.error : "inProgress" in value ? PlanStepStatus.inProgress : value;
}
function from_candid_variant_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    deployment: null;
} | {
    fileSystem: null;
} | {
    gitHub: null;
}): Tool {
    return "deployment" in value ? Tool.deployment : "fileSystem" in value ? Tool.fileSystem : "gitHub" in value ? Tool.gitHub : value;
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ErrorLog>): Array<ErrorLog> {
    return value.map((x)=>from_candid_ErrorLog_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LogEntry>): Array<LogEntry> {
    return value.map((x)=>from_candid_LogEntry_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MemoryEntry>): Array<MemoryEntry> {
    return value.map((x)=>from_candid_MemoryEntry_n42(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Message>): Array<Message> {
    return value.map((x)=>from_candid_Message_n47(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PlanStep>): Array<PlanStep> {
    return value.map((x)=>from_candid_PlanStep_n54(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ToolConnection>): Array<ToolConnection> {
    return value.map((x)=>from_candid_ToolConnection_n59(_uploadFile, _downloadFile, x));
}
function to_candid_AgentConfigDTO_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AgentConfigDTO): _AgentConfigDTO {
    return to_candid_record_n64(_uploadFile, _downloadFile, value);
}
function to_candid_ErrorLogDTO_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ErrorLogDTO): _ErrorLogDTO {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_ErrorType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ErrorType): _ErrorType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_LogEntryInput_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LogEntryInput): _LogEntryInput {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_LogStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LogStatus): _LogStatus {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_MemoryEntryDTO_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MemoryEntryDTO): _MemoryEntryDTO {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_MemoryType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MemoryType): _MemoryType {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_MessageInput_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageInput): _MessageInput {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_PlanStepDTO_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlanStepDTO): _PlanStepDTO {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_PlanStepStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlanStepStatus): _PlanStepStatus {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_RunMode_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RunMode): _RunMode {
    return to_candid_variant_n66(_uploadFile, _downloadFile, value);
}
function to_candid_TaskType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskType): _TaskType {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_ToolConnectionDTO_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ToolConnectionDTO): _ToolConnectionDTO {
    return to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_Tool_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Tool): _Tool {
    return to_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    content: string;
    memoryType: MemoryType;
}): {
    content: string;
    memoryType: _MemoryType;
} {
    return {
        content: value.content,
        memoryType: to_candid_MemoryType_n11(_uploadFile, _downloadFile, value.memoryType)
    };
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    content: string;
    role: Role;
    taskType: TaskType;
}): {
    content: string;
    role: _Role;
    taskType: _TaskType;
} {
    return {
        content: value.content,
        role: to_candid_Role_n15(_uploadFile, _downloadFile, value.role),
        taskType: to_candid_TaskType_n17(_uploadFile, _downloadFile, value.taskType)
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resolved: boolean;
    errorType: ErrorType;
    message: string;
}): {
    resolved: boolean;
    errorType: _ErrorType;
    message: string;
} {
    return {
        resolved: value.resolved,
        errorType: to_candid_ErrorType_n3(_uploadFile, _downloadFile, value.errorType),
        message: value.message
    };
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: PlanStepStatus;
    description: string;
    stepNumber: bigint;
}): {
    status: _PlanStepStatus;
    description: string;
    stepNumber: bigint;
} {
    return {
        status: to_candid_PlanStepStatus_n21(_uploadFile, _downloadFile, value.status),
        description: value.description,
        stepNumber: value.stepNumber
    };
}
function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tool: Tool;
    connected: boolean;
}): {
    tool: _Tool;
    connected: boolean;
} {
    return {
        tool: to_candid_Tool_n25(_uploadFile, _downloadFile, value.tool),
        connected: value.connected
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: LogStatus;
    message: string;
}): {
    status: _LogStatus;
    message: string;
} {
    return {
        status: to_candid_LogStatus_n7(_uploadFile, _downloadFile, value.status),
        message: value.message
    };
}
function to_candid_record_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    learningScore: bigint;
    mode: RunMode;
}): {
    learningScore: bigint;
    mode: _RunMode;
} {
    return {
        learningScore: value.learningScore,
        mode: to_candid_RunMode_n65(_uploadFile, _downloadFile, value.mode)
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MemoryType): {
    action: null;
} | {
    preference: null;
} | {
    session: null;
} {
    return value == MemoryType.action ? {
        action: null
    } : value == MemoryType.preference ? {
        preference: null
    } : value == MemoryType.session ? {
        session: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    agent: null;
} | {
    user: null;
} {
    return value == Role.agent ? {
        agent: null
    } : value == Role.user ? {
        user: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskType): {
    deployment: null;
} | {
    search: null;
} | {
    coding: null;
} | {
    analysis: null;
} {
    return value == TaskType.deployment ? {
        deployment: null
    } : value == TaskType.search ? {
        search: null
    } : value == TaskType.coding ? {
        coding: null
    } : value == TaskType.analysis ? {
        analysis: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlanStepStatus): {
    pending: null;
} | {
    done: null;
} | {
    error: null;
} | {
    inProgress: null;
} {
    return value == PlanStepStatus.pending ? {
        pending: null
    } : value == PlanStepStatus.done ? {
        done: null
    } : value == PlanStepStatus.error ? {
        error: null
    } : value == PlanStepStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Tool): {
    deployment: null;
} | {
    fileSystem: null;
} | {
    gitHub: null;
} {
    return value == Tool.deployment ? {
        deployment: null
    } : value == Tool.fileSystem ? {
        fileSystem: null
    } : value == Tool.gitHub ? {
        gitHub: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ErrorType): {
    toolFailure: null;
} | {
    logic: null;
} | {
    timeout: null;
} | {
    parsing: null;
} {
    return value == ErrorType.toolFailure ? {
        toolFailure: null
    } : value == ErrorType.logic ? {
        logic: null
    } : value == ErrorType.timeout ? {
        timeout: null
    } : value == ErrorType.parsing ? {
        parsing: null
    } : value;
}
function to_candid_variant_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RunMode): {
    normal: null;
} | {
    deep: null;
} | {
    caffeine: null;
} {
    return value == RunMode.normal ? {
        normal: null
    } : value == RunMode.deep ? {
        deep: null
    } : value == RunMode.caffeine ? {
        caffeine: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LogStatus): {
    completed: null;
} | {
    error: null;
} | {
    running: null;
} {
    return value == LogStatus.completed ? {
        completed: null
    } : value == LogStatus.error ? {
        error: null
    } : value == LogStatus.running ? {
        running: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
